[package]
name = "confidence"
version = "0.1.0"
authors = ["Alex Sayers <alex@asayers.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
special = "0.8.1"
approx = "0.3.2"
